import numpy as np
np.random.seed(1)
a=np.random.rand(120)
a=a.reshape(12,10)
print(a.mean(axis=0))
print(a.sum(axis=0))
print(a.std(axis=0),'\n')
print(a.mean(axis=1))
print(a.sum(axis=1))
print(a.std(axis=0))